#!/bin/sh

### BEGIN INIT INFO
# Provides:         smartcone
# Required-Start:   $local_fs $remote_fs $network $time
# Required-Stop:
# Should-Stop:
# X-Start-Before:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Smart Cone node.js server.
# Description: This includes the smart-cone-api and the field-trainer frontend
### END INIT INFO

case "$1" in
stop)
    echo "Killing Smart Cone service."
    sudo killall node
    date > /var/tmp/last-stop-time
    ;;

start)
    killall node
    echo "Checking for updates"
    ft-update
    ec=$?
    if [ $ec -eq 42 ]; then
	    echo "ft-update needed to update itself, rerunning"
	    ft-update
	    ec=$?
    fi
    if [ $ec -eq 0 ]; then
	    echo "Update client successful"

	    echo "Starting Smart Cone service."
	    date > /var/tmp/last-start-time
	    node /opt/smart-cone-api/dist/smart-cone-api/src/main.js &
	    node /opt/serve-frontend/index.js &
    else
	    echo "Failed to update! Giving up!"
	    echo "Failed to update" > /var/tmp/smartcone-failed
	    date > /var/tmp/last-start-time
    fi
    ;;

restart)
    stop
    start
    ;;

*)
    echo "Usage: ${0:-} {start|stop|restart}" >&2
    exit 1
    ;;
esac
