#!/bin/sh

### BEGIN INIT INFO
# Provides:         fieldcone
# Required-Start:   $local_fs $remote_fs $network $time
# Required-Stop:
# Should-Stop:
# X-Start-Before: 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Field Cone node.js server
# Description:
### END INIT INFO

case "$1" in
stop)
    echo "Killing Field Cone service."
    sudo killall node
    date > /var/tmp/last-stop-time
    ;;

start)
    echo "Starting Field Cone service."
    date > /var/tmp/last-start-time
    cd /home/pi/FT-WEB/field-cone-api && npm run prod &
    ;;

restart)
    stop
    start
    ;;

*)
    echo "Usage: ${0:-} {start|stop|restart}" >&2
    exit 1
    ;;
esac