#!/bin/sh

### BEGIN INIT INFO
# Provides:         smartcone
# Required-Start:   $local_fs $remote_fs $network $time
# Required-Stop:
# Should-Stop:
# X-Start-Before: 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Smart Cone node.js server.
# Description: This includes the smart-cone-api and the field-trainer frontend
### END INIT INFO

case "$1" in
stop)
    echo "Killing Field Cone service."
    echo "TODO: WE SHOULD BE KILLING THE SERVICE HERE!!!!"
    date > /var/tmp/last-stop-time
    ;;

start)
    echo "Starting Field Cone service."
    echo "TODO: WE SHOULD BE KILLING THE SERVICE HERE!!!!"
    date > /var/tmp/last-start-time
    cd /home/pi/FT-WEB/serve-frontend/ && node index.js &
    cd /home/pi/FT-WEB/smart-cone-api && npm run prod &
    ;;

*)
    echo "Usage: ${0:-} {start|stop}" >&2
    exit 1
    ;;
esac
