#!/bin/sh

### BEGIN INIT INFO
# Provides:         fieldcone
# Required-Start:   $local_fs $remote_fs $network $time
# Required-Stop:
# Should-Stop:
# X-Start-Before:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Field Cone node.js server
# Description:
### END INIT INFO

case "$1" in
stop)
    echo "Killing Field Cone service."
    killall node
    date > /var/tmp/last-stop-time
    ;;

start)
    killall node

    . /var/tmp/ft_environment
    ft-update
    ec=$?
    if [ $ec -eq 42 ]; then
        echo "ft-update needed to update itself, rerunning"
        ft-update
        ec=$?
    fi
    if [ $ec -eq 0 ]; then
        echo "Update client successful"
    else
        echo "Update failed! But maybe we don't have internet access... still trying to launch"
    fi

    echo "Starting Field Cone service."
    date > /var/tmp/last-start-time
    export FIELD_CONE_SOCKET_URL=http://192.168.2.1:6000
    cd /opt/field-cone-api && npm run start:prod &
    ;;

restart)
    stop
    start
    ;;

*)
    echo "Usage: ${0:-} {start|stop|restart}" >&2
    exit 1
    ;;
esac